/** AI-CODING NOTE: Behavioral regression for stable shared project/object identities across stored Manual Trace views. */
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';
import '../../trace-project-package.js';
const source=await readFile(new URL('../../app-08.js',import.meta.url),'utf8');
const shape=(id,name)=>({id,type:'poly',name,role:'trace',description:`${name} contour`,closed:true,points:[{x:0,y:0},{x:100,y:0},{x:100,y:20},{x:0,y:20}],semantic:{feature_kind:'outer_contour'},references:[]});
function context(){const elements=new Map([['packageViewType',{value:'side',addEventListener(){}}],['packageViewStatus',{textContent:''}],['storePackageView',{addEventListener(){}}],['exportTraceProject',{disabled:false,addEventListener(){}}]]),S={schema_version:'engrove_manual_trace_v16',project_meta:{name:'Multi view'},img:{name:'side.png',width:400,height:200,dataUrl:'data:image/png;base64,iVBORw0KGgo='},shapes:[shape('side-outline','Side')],frame:{origin:{x:10,y:20},origin_metadata:{description:'Origin.'},axes:{x:'+image_x',y:'+out_of_screen',z:'-image_y'},scale:{unit_per_px:.5,source_length_px:200,source_real_length:100,reference_measure_id:'measure-reference'}},svgTrace:{}};const c={S,$:id=>elements.get(id)||null,clone:v=>JSON.parse(JSON.stringify(v)),ensureAllMeta(){},outObj:()=>({schema_version:S.schema_version,description:{en:'Synthetic trace.'},image:S.img,trace_frame:S.frame,shapes:S.shapes}),safeFileBase:v=>String(v||'project').replace(/[^A-Za-z0-9._-]+/g,'_'),PROJECT_SCHEMA:'engrove_trace_project_v2',EngroveTraceProjectPackage:globalThis.EngroveTraceProjectPackage,crypto:{randomUUID:(()=>{let n=0;return()=>`00000000-0000-4000-8000-${String(++n).padStart(12,'0')}`})()},alert:m=>{throw new Error(m)},console,setTimeout(){},elements};c.globalThis=c;return c}
test('side and top snapshots retain one stable project and object',()=>{const c=context();vm.runInNewContext(source,c,{filename:'app-08.js'});const side=c.captureCurrentPackageView(),pid=c.S.project_meta.package_project_id,oid=c.S.project_meta.package_object_id;c.elements.get('packageViewType').value='top';c.S.img={...c.S.img,name:'top.png'};c.S.shapes=[shape('top-outline','Top')];c.S.frame.axes={x:'+image_x',y:'+image_y',z:'+out_of_screen'};const top=c.captureCurrentPackageView(),m=c.manualTraceProjectModelFromWorkspace(false);assert.equal(c.S.project_meta.package_project_id,pid);assert.equal(c.S.project_meta.package_object_id,oid);assert.notEqual(side.trace.traceId,top.trace.traceId);assert.equal(JSON.stringify(m.traces.map(x=>x.view.viewType)),JSON.stringify(['side','top']));assert.ok(m.traces.every(x=>x.objectId===oid));assert.equal(m.projectId,pid);assert.equal(m.objectId,oid);assert.equal(m.assets.length,4)});
