/** AI-CODING NOTE: Production regressions for merged-schema rejection, canonical JSON assets, and locale-independent ordering. */
import assert from 'node:assert/strict';
import test from 'node:test';
import '../../trace-project-package.js';
import '../../trace-project-package-production.js';
import { loadSchemas, validatePackage } from './contract-validator.mjs';

const base=globalThis.EngroveTraceProjectPackage;
const production=globalThis.EngroveTraceProjectPackageProduction;
const at='2026-07-13T06:00:00Z';
const axis=(engineeringAxis,direction)=>({engineeringAxis,direction,meaning:`${engineeringAxis}${direction}`});
const frame={origin:{xMm:0,yMm:0,zMm:0,datumId:'datum-origin'},axes:{x:{meaning:'longitudinal',unitVector:{x:1,y:0,z:0}},y:{meaning:'lateral',unitVector:{x:0,y:1,z:0}},z:{meaning:'vertical',unitVector:{x:0,y:0,z:1}}},handedness:'right',lengthUnit:'mm',objectDirection:{axis:'X',positiveMeaning:'positive X',fromDatum:'datum-origin',toDatum:'datum-x'},datums:[{datumId:'datum-origin',name:'Origin',kind:'point',positionMm:{x:0,y:0,z:0},description:'Origin.',references:[]},{datumId:'datum-x',name:'Positive X',kind:'point',positionMm:{x:100,y:0,z:0},description:'Positive X.',references:[]}],references:[]};
function trace(id,type,axes,sidecar){return{schemaVersion:'1.0.0',traceId:id,objectId:'object-shared-001',view:{viewType:type,projection:'orthographic',geometricUse:'used_for_geometry',viewFrame:{originPx:{x:0,y:0},uAxis:axes[0],vAxis:axes[1],normalAxis:axes[2],pixelConvention:'u_right_v_down',engineeringOriginDatumId:'datum-origin'},sectionBinding:null},calibration:{unit:'mm',unitPerPx:.5,referenceMeasurementId:'measure-reference',sourcePixelLength:200,sourceRealLength:100,method:'known_dimension',provenance:{source:'synthetic',notes:['test']},toleranceMm:.01},geometry:{primaryContourId:`${id}-outline`,contours:[{contourId:`${id}-outline`,name:'Outline',description:'Synthetic outline.',geometry:{type:'polygon',points:[{x:0,y:0},{x:100,y:0},{x:100,y:20},{x:0,y:20}]},closed:true,role:'outer_contour',featureKind:'silhouette',references:[],sourceSvgElement:null,status:'primary'}],stations:[],datums:[],relations:[]},assets:{sourceImageAssetId:null,sourceSvgAssetId:null,sidecarAssetIds:[sidecar]},provenance:{producer:{name:'Engrove Manual Trace',version:'18.0.0'},originalSchema:'test',sourceFileName:`${id}.json`,sourceDigest:'0'.repeat(64),imageDimensions:{widthPx:400,heightPx:200},sourceViewBox:null,sourceSvgBinding:null,traceDescriptions:['test'],semanticNames:[id],aiHints:[],references:[],exportedAt:at,sourceFields:['workspace']}}}
function model(sidecarText='{"z":1,"a":{"y":2,"b":3}}') {const traces=[trace('trace-A_01','side',[axis('X',1),axis('Z',-1),axis('Y',1)],'asset-sidecar-A_01'),trace('trace-a.01','top',[axis('X',1),axis('Y',1),axis('Z',1)],'asset-sidecar-a.01')];return{projectId:'project-multiview-001',objectId:'object-shared-001',name:'Multi view',description:'Production contract test.',objectType:'generic_object',objectName:'Object',objectDescription:'Shared object.',createdAt:at,producer:{name:'Engrove Manual Trace',version:'18.0.0'},engineeringFrame:structuredClone(frame),traces,assets:traces.map((item,index)=>({assetId:item.assets.sidecarAssetIds[0],role:'sidecar',mediaType:'application/json',path:`assets/sidecars/${index?'a.01':'A_01'}-workspace.json`,text:sidecarText,traceIds:[item.traceId],originalFileName:'workspace.json'})),provenance:{producer:{name:'Engrove Manual Trace',version:'18.0.0'},originalSchema:'test',sourceFileName:'test.engrove-trace',exportedAt:at,sourceFields:['workspace'],notes:['test']},fieldDisposition:[{sourcePath:'workspace',status:'preserved_as_provenance',reason:'Retained.',targetPath:'assets.sidecars'}]}}
const options={schemaDirectory:'schema/trace-project-package'};
const clone=value=>structuredClone(value);

async function validPackage(sidecarText){return production.buildValidatedZipPackage(model(sidecarText),options)}

test('production package passes the merged contract validator',async()=>{const pkg=await validPackage();const schemas=await loadSchemas(new URL('../../../../schema/trace-project-package/',import.meta.url));const result=validatePackage({manifest:pkg.manifest,entries:pkg.entries},schemas);assert.equal(result.ok,true,JSON.stringify(result,null,2))});

test('production rejects schema-invalid project data',async()=>{const pkg=await validPackage();delete pkg.project.provenance;pkg.entries['project.json'].content=pkg.project;await assert.rejects(production.validateMergedSchemas(pkg,options),error=>error.code==='CONTRACT_VALIDATION_FAILED'&&error.diagnostics.some(item=>item.includes('project.provenance')))});

test('production rejects schema-invalid trace data',async()=>{const pkg=await validPackage();const path=pkg.project.traceFiles[0].path;delete pkg.entries[path].content.provenance;await assert.rejects(production.validateMergedSchemas(pkg,options),error=>error.code==='CONTRACT_VALIDATION_FAILED'&&error.diagnostics.some(item=>item.includes('provenance')))});

test('production rejects schema-invalid manifest data',async()=>{const pkg=await validPackage();delete pkg.manifest.packageFormat;await assert.rejects(production.validateMergedSchemas(pkg,options),error=>error.code==='CONTRACT_VALIDATION_FAILED'&&error.diagnostics.some(item=>item.includes('manifest.packageFormat')))});

test('JSON sidecar insertion order produces identical bytes hashes and ZIP',async()=>{const first=await validPackage(JSON.stringify({z:1,a:{y:2,b:3}}));const second=await validPackage(JSON.stringify({a:{b:3,y:2},z:1}));const path='assets/sidecars/A_01-workspace.json';assert.equal(first.entries[path].content,second.entries[path].content);assert.equal(first.manifest.files.find(file=>file.path===path).sha256,second.manifest.files.find(file=>file.path===path).sha256);assert.deepEqual(first.zipBytes,second.zipBytes)});

test('code-unit ordering is explicit for mixed case and punctuation',async()=>{const values=['a_1','A-1','a.1','A_1','a-1','A.1'];const expected=[...values].sort((a,b)=>a<b?-1:a>b?1:0);assert.deepEqual([...values].sort(production.compareCodeUnits),expected);const pkg=await validPackage();assert.deepEqual(pkg.project.traceFiles.map(item=>item.traceId),['trace-A_01','trace-a.01']);assert.deepEqual(pkg.manifest.files,[...pkg.manifest.files].sort((a,b)=>{const rank=role=>({project:0,trace:1,source_image:2,source_svg:3,sidecar:4,readme:5}[role]??9);return rank(a.role)-rank(b.role)||production.compareCodeUnits(a.path,b.path)}))});
