/** AI-CODING NOTE: Focused production package/ZIP determinism, integrity, contract, and limit regressions. */
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';
import '../../trace-project-package.js';
import { canonicalJsonBytes as contractBytes, loadSchemas, validatePackage } from './contract-validator.mjs';
const api=globalThis.EngroveTraceProjectPackage,schemas=await loadSchemas(new URL('../../../../schema/trace-project-package/',import.meta.url)),at='2026-07-12T12:00:00Z';
const frame={origin:{xMm:0,yMm:0,zMm:0,datumId:'datum-origin'},axes:{x:{meaning:'longitudinal',unitVector:{x:1,y:0,z:0}},y:{meaning:'lateral',unitVector:{x:0,y:1,z:0}},z:{meaning:'vertical',unitVector:{x:0,y:0,z:1}}},handedness:'right',lengthUnit:'mm',objectDirection:{axis:'X',positiveMeaning:'positive X',fromDatum:'datum-origin',toDatum:'datum-x'},datums:[{datumId:'datum-origin',name:'Origin',kind:'point',positionMm:{x:0,y:0,z:0},description:'Origin datum.',references:[]},{datumId:'datum-x',name:'X datum',kind:'point',positionMm:{x:100,y:0,z:0},description:'Positive X datum.',references:[]}],references:[]};
function trace(id,type,axes){return{schemaVersion:'1.0.0',traceId:id,objectId:'object-shared-001',view:{viewType:type,projection:'orthographic',geometricUse:'used_for_geometry',viewFrame:{originPx:{x:0,y:0},uAxis:axes[0],vAxis:axes[1],normalAxis:axes[2],pixelConvention:'u_right_v_down',engineeringOriginDatumId:'datum-origin'},sectionBinding:null},calibration:{unit:'mm',unitPerPx:.5,referenceMeasurementId:'measure-reference',sourcePixelLength:200,sourceRealLength:100,method:'known_dimension',provenance:{source:'synthetic',notes:['test']},toleranceMm:.01},geometry:{primaryContourId:`${id}-outline`,contours:[{contourId:`${id}-outline`,name:'Outline',description:'Synthetic outline.',geometry:{type:'polygon',points:[{x:0,y:0},{x:100,y:0},{x:100,y:20},{x:0,y:20}]},closed:true,role:'outer_contour',featureKind:'silhouette',references:[],sourceSvgElement:null,status:'primary'}],stations:[],datums:[],relations:[]},assets:{sourceImageAssetId:'asset-image-001',sourceSvgAssetId:null,sidecarAssetIds:[]},provenance:{producer:{name:'Engrove Manual Trace',version:'18.0.0'},originalSchema:'test',sourceFileName:`${id}.json`,sourceDigest:'0000000000000000000000000000000000000000000000000000000000000000',imageDimensions:{widthPx:400,heightPx:200},sourceViewBox:null,sourceSvgBinding:null,traceDescriptions:['test'],semanticNames:[id],aiHints:[],references:[],exportedAt:at,sourceFields:['shapes']}}}
function model(){const a=x=>({engineeringAxis:x[0],direction:+x.slice(1),meaning:x});return{projectId:'project-multiview-001',objectId:'object-shared-001',name:'Multi view',description:'Deterministic multi-view test.',objectType:'generic_object',objectName:'Object',objectDescription:'Shared object.',createdAt:at,producer:{name:'Engrove Manual Trace',version:'18.0.0'},engineeringFrame:structuredClone(frame),traces:[trace('trace-side-001','side',[a('X1'),a('Z-1'),a('Y1')]),trace('trace-top-001','top',[a('X1'),a('Y1'),a('Z1')])],assets:[{assetId:'asset-image-001',role:'source_image',mediaType:'image/png',path:'assets/images/reference.png',bytes:new Uint8Array([137,80,78,71]),traceIds:['trace-side-001','trace-top-001'],originalFileName:'reference.png'}],provenance:{producer:{name:'Engrove Manual Trace',version:'18.0.0'},originalSchema:'test',sourceFileName:'test.engrove-trace',exportedAt:at,sourceFields:['shapes'],notes:['test']},fieldDisposition:[{sourcePath:'shapes',status:'used_for_geometry',reason:'Mapped.',targetPath:'traces.*.geometry'}]}}
function zipEntries(b){const out=[],d=new TextDecoder();let o=0;while(new DataView(b.buffer,b.byteOffset+o).getUint32(0,true)===0x04034b50){const v=new DataView(b.buffer,b.byteOffset+o),n=v.getUint16(26,true),x=v.getUint16(28,true),s=v.getUint32(18,true),p=o+30;out.push({path:d.decode(b.subarray(p,p+n)),bytes:b.slice(p+n+x,p+n+x+s)});o=p+n+x+s;if(o+4>b.length)break}return out}
const build=o=>api.buildZipPackage(model(),o);
test('round trip and deterministic ZIP ordering',async()=>{const r=await build({readmeText:'Read me.\n'}),z=zipEntries(r.zipBytes);assert.deepEqual(z.map(x=>x.path),r.orderedPaths);assert.deepEqual(JSON.parse(new TextDecoder().decode(z[0].bytes)),r.manifest)});
test('repeated logical input is byte-identical',async()=>{const a=model(),b=model();b.traces.reverse();assert.deepEqual((await api.buildZipPackage(a)).zipBytes,(await api.buildZipPackage(b)).zipBytes)});
test('multiple traces share one object',async()=>{const r=await build();assert.equal(r.project.traceFiles.length,2);assert.ok(r.project.traceFiles.every(x=>x.objectId==='object-shared-001'))});
test('canonical JSON sorts keys and ends newline',()=>assert.equal(new TextDecoder().decode(api.canonicalJsonBytes({z:1,a:{y:2,b:3}})),'{\n  "a": {\n    "b": 3,\n    "y": 2\n  },\n  "z": 1\n}\n'));
test('hashes and sizes cover payloads',async()=>{const r=await build();for(const f of r.manifest.files){const e=r.entries[f.path],b=e.kind==='json'?contractBytes(e.content):Buffer.from(e.content,e.kind==='base64'?'base64':'utf8');assert.equal(f.sizeBytes,b.length);assert.equal(f.sha256,createHash('sha256').update(b).digest('hex'))}});
test('contract validation and asset integrity',async()=>{const r=await build();const v=validatePackage({manifest:r.manifest,entries:r.entries},schemas);assert.equal(v.ok,true,JSON.stringify(v,null,2));assert.equal(r.project.assets[0].sha256,r.manifest.files.find(x=>x.assetId==='asset-image-001').sha256)});
test('path traversal and absolute paths rejected',async()=>{for(const p of ['../x','/x','C:\\x','assets/../x']){const m=model();m.assets[0].path=p;await assert.rejects(api.buildVirtualPackage(m),e=>e.code==='UNSAFE_PATH')}});
test('duplicate and normalized collision rejected',async()=>{const m=model();m.assets.push({...m.assets[0],assetId:'asset-image-002'});m.traces[0].assets.sidecarAssetIds.push('asset-image-002');await assert.rejects(api.buildVirtualPackage(m),e=>e.code==='DUPLICATE_ENTRY');assert.throws(()=>api.createDeterministicZip([{path:'A.txt',bytes:new Uint8Array(1)},{path:'a.txt',bytes:new Uint8Array(1)}]),e=>e.code==='NORMALIZED_PATH_COLLISION')});
test('file count limit',async()=>assert.rejects(build({limits:{maxFileCount:2}}),e=>e.code==='FILE_COUNT_LIMIT'));
test('total size limit',async()=>assert.rejects(build({limits:{maxTotalUncompressedBytes:10}}),e=>e.code==='TOTAL_SIZE_LIMIT'));
test('individual size limit',async()=>assert.rejects(build({limits:{maxIndividualFileBytes:2}}),e=>e.code==='INDIVIDUAL_FILE_SIZE_LIMIT'));
test('compression ratio protection',()=>assert.throws(()=>api.validateEntryLimits([{path:'x',bytes:new Uint8Array(1000),compressedSize:1}],{maxCompressionRatio:100}),e=>e.code==='COMPRESSION_RATIO_LIMIT'));
