/**
 * AI-CODING NOTE:
 * Responsibility: Manual Trace shared state and function definitions, chunk 4 of 7.
 * Dependency: Classic scripts share one global lexical environment and must load in numeric order.
 * Safe edits: Preserve identifiers, ordering, schemas, provenance, and browser-local behavior.
 * Do not: Load independently, reorder scripts, or weaken SVG sanitization.
 */
"use strict";
function autoSmoothPath(s,closed=s.closed){let ns=s.nodes||[],n=ns.length;if(n<2)return s;for(let i=0;i<n;i++){let P=ns[i];if(P.auto===false)continue;let prev=i>0?ns[i-1]:(closed?ns[n-1]:null),next=i<n-1?ns[i+1]:(closed?ns[0]:null);if(prev&&next){let vx=next.x-prev.x,vy=next.y-prev.y,len=Math.hypot(vx,vy)||1,ux=vx/len,uy=vy/len,lp=d(P,prev),ln=d(P,next),cap=Math.min(lp,ln)*.48,hin=Math.min(lp/3,cap),hout=Math.min(ln/3,cap);P.in={x:P.x-ux*hin,y:P.y-uy*hin};P.out={x:P.x+ux*hout,y:P.y+uy*hout};P.mode="smooth";P.auto=true}else if(next){let vx=next.x-P.x,vy=next.y-P.y,len=Math.hypot(vx,vy)||1,ux=vx/len,uy=vy/len,h=Math.min(len/3,len*.42);P.in={x:P.x,y:P.y};P.out={x:P.x+ux*h,y:P.y+uy*h};P.mode="smooth";P.auto=true}else if(prev){let vx=P.x-prev.x,vy=P.y-prev.y,len=Math.hypot(vx,vy)||1,ux=vx/len,uy=vy/len,h=Math.min(len/3,len*.42);P.in={x:P.x-ux*h,y:P.y-uy*h};P.out={x:P.x,y:P.y};P.mode="smooth";P.auto=true}}return s}
function addPen(p,e){let corner=!!(e&&e.shiftKey);const node=q=>({x:q.x,y:q.y,in:{x:q.x,y:q.y},out:{x:q.x,y:q.y},auto:!corner,mode:corner?"corner":"smooth"});if(!S.cur){if(S.anchor){let a=clone(S.anchor);S.anchor=null;S.cur={id:id("path"),type:"path",name:"bezier_path",role:"trace",closed:false,nodes:[node(a),node(p)]};autoSmoothPath(S.cur);return}S.cur={id:id("path"),type:"path",name:"bezier_path",role:"trace",closed:false,nodes:[node(p)]};return}S.cur.nodes.push(node(p));autoSmoothPath(S.cur)}
function d(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function seg(p,a,b){let vx=b.x-a.x,vy=b.y-a.y,wx=p.x-a.x,wy=p.y-a.y,t=Math.max(0,Math.min(1,(wx*vx+wy*vy)/(vx*vx+vy*vy||1)));return Math.hypot(p.x-(a.x+t*vx),p.y-(a.y+t*vy))}
function sample(s,n=16){let pts=[];if(!s.nodes?.length)return pts;pts.push({x:s.nodes[0].x,y:s.nodes[0].y});let N=s.nodes.length-1+(s.closed?1:0);for(let k=0;k<N;k++){let a=s.nodes[k],b=s.nodes[(k+1)%s.nodes.length],c1=a.out||a,c2=b.in||b;for(let i=1;i<=n;i++){let t=i/n,m=1-t;pts.push({x:m*m*m*a.x+3*m*m*t*c1.x+3*m*t*t*c2.x+t*t*t*b.x,y:m*m*m*a.y+3*m*m*t*c1.y+3*m*t*t*c2.y+t*t*t*b.y})}}return pts}
function samplePathCount(s,count=64){let ns=s?.nodes||[],segCount=ns.length-1+(s?.closed?1:0),out=[];if(!ns.length||segCount<=0||count<=0)return out;let total=Math.max(2,Math.floor(count)),den=s.closed?total:(total-1);for(let i=0;i<total;i++){let u=s.closed?(i*segCount/total):(i*segCount/den),k=Math.min(segCount-1,Math.floor(u)),t=Math.min(1,u-k),a=ns[k],b=ns[(k+1)%ns.length],c1=a.out||a,c2=b.in||b,m=1-t;out.push({x:m*m*m*a.x+3*m*m*t*c1.x+3*m*t*t*c2.x+t*t*t*b.x,y:m*m*m*a.y+3*m*m*t*c1.y+3*m*t*t*c2.y+t*t*t*b.y})}return out}
function hitHandles(s,p){let best=null,bd=1e9,chk=(kind,index,q)=>{let dd=d(p,q);if(dd<bd){bd=dd;best={kind,index,point:q,dist:dd}}};if(s.type==="station"){let ori=s.orientation||"vertical";if(ori==="horizontal"){let y=s.y??s.y1??0;chk("station_start",0,{x:s.x1??0,y});chk("station_mid",1,{x:((s.x1??0)+(s.x2??(S.img?.width||1000)))/2,y});chk("station_end",2,{x:s.x2??(S.img?.width||1000),y})}else{chk("station_top",0,{x:s.x,y:s.y1??0});chk("station_mid",1,{x:s.x,y:((s.y1??0)+(s.y2??(S.img?.height||1000)))/2});chk("station_bottom",2,{x:s.x,y:s.y2??(S.img?.height||1000)})}}else if(s.type==="line")s.points.forEach((q,i)=>chk("point",i,q));else if(s.type==="measure")s.points.forEach((q,i)=>chk("point",i,q));else if(s.type==="poly"||s.type==="mask"||s.type==="zone")s.points.forEach((q,i)=>chk("point",i,q));else if(s.type==="rect")corners(s).forEach((q,i)=>chk("corner",i,q));else if(s.type==="circle"){chk("center",0,{x:s.cx,y:s.cy});chk("radius",1,{x:s.cx+s.r,y:s.cy})}else if(s.type==="path")s.nodes.forEach((n,i)=>{chk("node",i,n);if(n.in)chk("in",i,n.in);if(n.out)chk("out",i,n.out)});return best}
function shapeDist(s,p){if(s.type==="station"){let ori=s.orientation||"vertical";return ori==="horizontal"?seg(p,{x:s.x1??0,y:s.y??s.y1??0},{x:s.x2??(S.img?.width||1000),y:s.y??s.y1??0}):seg(p,{x:s.x,y:s.y1??0},{x:s.x,y:s.y2??(S.img?.height||1000)})}if(s.type==="line"||s.type==="measure")return seg(p,s.points[0],s.points[1]);if(s.type==="rect"){let ps=corners(s),m=1e9;for(let i=0;i<4;i++)m=Math.min(m,seg(p,ps[i],ps[(i+1)%4]));return m}if(s.type==="circle")return Math.abs(d(p,{x:s.cx,y:s.cy})-Math.abs(s.r));if(s.type==="poly"||s.type==="mask"||s.type==="zone"){let m=1e9;for(let i=1;i<s.points.length;i++)m=Math.min(m,seg(p,s.points[i-1],s.points[i]));if(s.closed&&s.points.length>2)m=Math.min(m,seg(p,s.points.at(-1),s.points[0]));return m}if(s.type==="path"){let ps=sample(s,12),m=1e9;for(let i=1;i<ps.length;i++)m=Math.min(m,seg(p,ps[i-1],ps[i]));return m}return 1e9}
function hit(p){let best=null,bd=1e9;for(let s of S.shapes){let h=hitHandles(s,p);if(h&&h.dist<bd){best={shape:s,...h};bd=h.dist}}if(best&&bd<14/S.view.s)return best;for(let s of S.shapes){let dd=shapeDist(s,p);if(dd<bd){best={shape:s,kind:"shape",dist:dd};bd=dd}}return bd<12/S.view.s?best:null}
function hitNode(p,includeCurrent=true){let best=null,bd=1e9,scan=(s,current=false)=>{if(!s)return;let h=hitHandles(s,p);if(h&&h.dist<bd){best={shape:s,current,...h};bd=h.dist}};if(includeCurrent)scan(S.cur,true);for(let s of S.shapes)scan(s,false);return best&&bd<18/S.view.s?best:null}
function contactPoints(s){let a=[];if(!s)return a;if(s.type==="station"){let ori=s.orientation||"vertical";if(ori==="horizontal"){let y=s.y??s.y1??0;a.push({x:s.x1??0,y},{x:s.x2??(S.img?.width||1000),y},{x:((s.x1??0)+(s.x2??(S.img?.width||1000)))/2,y})}else a.push({x:s.x,y:s.y1??0},{x:s.x,y:s.y2??(S.img?.height||1000)},{x:s.x,y:((s.y1??0)+(s.y2??(S.img?.height||1000)))/2})}else if(s.type==="line"||s.type==="measure")a.push(...s.points);else if(s.type==="poly"||s.type==="mask"||s.type==="zone")a.push(...s.points);else if(s.type==="rect")a.push(...corners(s));else if(s.type==="circle")a.push({x:s.cx,y:s.cy},{x:s.cx+s.r,y:s.cy});else if(s.type==="path")s.nodes.forEach(n=>a.push({x:n.x,y:n.y}));return a}
function snapPoint(p,opt={}){S.snapHit=null;if(!S.snap||opt.off)return p;let best=null,bd=1e9,thr=(S.snapPx||14)/S.view.s;let scan=s=>{for(let q of contactPoints(s)){let dd=d(p,q);if(dd<bd){bd=dd;best=q}}};if(S.frame.origin){let dd=d(p,S.frame.origin);if(dd<bd){bd=dd;best=S.frame.origin}}S.shapes.forEach(scan);if(opt.includeCurrent&&S.cur)scan(S.cur);if(best&&bd<=thr){S.snapHit={x:best.x,y:best.y,dist:bd};return{x:best.x,y:best.y}}return p}
function snapDraw(){if(!S.snapHit)return;cx.save();cx.strokeStyle="#6b93ff";cx.fillStyle="#6b93ff33";cx.lineWidth=2/S.view.s;cx.beginPath();cx.arc(S.snapHit.x,S.snapHit.y,(S.snapPx||14)/S.view.s,0,Math.PI*2);cx.fill();cx.stroke();cx.beginPath();cx.moveTo(S.snapHit.x-7/S.view.s,S.snapHit.y);cx.lineTo(S.snapHit.x+7/S.view.s,S.snapHit.y);cx.moveTo(S.snapHit.x,S.snapHit.y-7/S.view.s);cx.lineTo(S.snapHit.x,S.snapHit.y+7/S.view.s);cx.stroke();cx.restore()}
function snapStationCoord(p,ori="vertical",excludeId=null){if(!S.snap)return stationCoordFromPoint(p,ori);let raw=stationCoordFromPoint(p,ori),best=null,bd=1e9,thr=(S.snapPx||14)/S.view.s;if(S.frame.origin){let oc=ori==="horizontal"?S.frame.origin.y:S.frame.origin.x,dd=Math.abs(raw-oc);if(dd<bd){bd=dd;best=oc}}for(let s of S.shapes){if(s.id===excludeId)continue;if(s.type==="station"){let sc=(s.orientation||"vertical")==="horizontal"?(s.y??s.y1??0):s.x,dd=Math.abs(raw-sc);if(dd<bd){bd=dd;best=sc}}for(let q of contactPoints(s)){let qc=ori==="horizontal"?q.y:q.x,dd=Math.abs(raw-qc);if(dd<bd){bd=dd;best=qc}}}if(best!==null&&bd<=thr){S.snapHit=ori==="horizontal"?{x:p.x,y:best,dist:bd}:{x:best,y:p.y,dist:bd};return best}return raw}
function moveWhole(s,dx,dy,o){if(s.type==="station"){let ori=s.orientation||o.orientation||"vertical";if(ori==="horizontal"){let y=(o.y??o.y1??0)+dy;s.orientation=ori;s.y=y;s.y1=y;s.y2=y;s.x1=(o.x1??0)+dx;s.x2=(o.x2??(S.img?.width||1000))+dx}else{let x=(o.x??o.x1??0)+dx;s.orientation=ori;s.x=x;s.x1=x;s.x2=x;s.y1=(o.y1??0)+dy;s.y2=(o.y2??(S.img?.height||1000))+dy}}else if(s.type==="line"||s.type==="measure")s.points=o.points.map(p=>({x:p.x+dx,y:p.y+dy}));else if(s.type==="poly"||s.type==="mask"||s.type==="zone")s.points=o.points.map(p=>({x:p.x+dx,y:p.y+dy}));else if(s.type==="rect"){s.x=o.x+dx;s.y=o.y+dy}else if(s.type==="circle"){s.cx=o.cx+dx;s.cy=o.cy+dy}else if(s.type==="path")s.nodes=o.nodes.map(n=>({x:n.x+dx,y:n.y+dy,in:n.in?{x:n.in.x+dx,y:n.in.y+dy}:null,out:n.out?{x:n.out.x+dx,y:n.out.y+dy}:null}))}
function edit(h,p,start,o){let s=h.current?S.cur:S.shapes.find(x=>x.id===h.shape.id),dx=p.x-start.x,dy=p.y-start.y;if(!s)return;if(h.kind==="shape"){moveWhole(s,dx,dy,o);return}if(s.type==="station"){let ori=s.orientation||o.orientation||"vertical",sc=snapStationCoord(p,ori,s.id);s.orientation=ori;if(ori==="horizontal"){s.y=sc;if(h.kind==="shape"){s.x1=(o.x1??0)+dx;s.x2=(o.x2??(S.img?.width||1000))+dx}else if(h.kind==="station_start")s.x1=p.x;else if(h.kind==="station_end")s.x2=p.x}else{s.x=sc;if(h.kind==="shape"){s.y1=(o.y1??0)+dy;s.y2=(o.y2??(S.img?.height||1000))+dy}else if(h.kind==="station_top")s.y1=p.y;else if(h.kind==="station_bottom")s.y2=p.y}}else if(s.type==="line")s.points[h.index]=p;else if(s.type==="measure"){s.points[h.index]=S.measureSnap?measureSnapPoint(p,{altKey:false}):p;updateMeasurements()}else if(s.type==="poly"||s.type==="mask"||s.type==="zone")s.points[h.index]=p;else if(s.type==="rect"){let op=corners(o)[(h.index+2)%4];s.x=Math.min(p.x,op.x);s.y=Math.min(p.y,op.y);s.w=Math.abs(p.x-op.x);s.h=Math.abs(p.y-op.y)}else if(s.type==="circle"){if(h.kind==="center"){s.cx=o.cx+dx;s.cy=o.cy+dy}else s.r=d(p,{x:s.cx,y:s.cy})}else if(s.type==="path"){let n=s.nodes[h.index],on=o.nodes[h.index];if(h.kind==="node"){let ndx=p.x-on.x,ndy=p.y-on.y;n.x=p.x;n.y=p.y;if(n.in&&on.in){n.in.x=on.in.x+ndx;n.in.y=on.in.y+ndy}if(n.out&&on.out){n.out.x=on.out.x+ndx;n.out.y=on.out.y+ndy}}if(h.kind==="in"){n.in=p;n.auto=false;n.mode="manual"}if(h.kind==="out"){n.out=p;n.auto=false;n.mode="manual"}if(h.kind==="node"&&n.auto!==false)autoSmoothPath(s,s.closed)}}
function originHit(p){return S.frame.origin&&d(p,S.frame.origin)<20/S.view.s}
function moveOriginTo(p,orig,start){if(!orig)return;S.frame.origin={x:orig.x+(p.x-start.x),y:orig.y+(p.y-start.y)};updateStationPositionsFromOrigin()}
function clickToolAt(raw,e){let p=snapPoint(raw,{off:e&&e.altKey});if(S.tool==="tracepick"){let c=svgCandidateAt(raw);if(c){ensureSvgTrace().activeId=c.id;c.status=e&&e.altKey?"ignore":(e&&e.shiftKey?(c.status==="include"?"ignore":"include"):"include");renderAutoTracePanel();draw()}return}if(S.tool==="nodeadd"){smartInsertNode(raw);return}if(S.tool==="nodedelete"){smartDeleteNode(raw);return}if(S.tool==="select"){let h=hit(p);if(h){S.sel=h.shape.id;hist();S.drag={mode:"edit",hit:h,start:p,orig:clone(h.shape)}}else S.sel=null;sync(false);draw();return}if(S.tool==="origin"){setOrigin(p);return}if(S.tool==="station"){addStationAt(p);return}if(S.tool==="measure"){let p2=measureSnapPoint(raw,e);if(S.cur&&S.cur.type==="measure"){S.cur.points[1]=p2;commit();return}if(S.anchor){let a=clone(S.anchor);S.anchor=null;S.cur={id:id("measure"),type:"measure",name:"measure",role:"measurement",points:[a,p2],unit:ensureScale().unit||"mm",is_scale_reference:false};commit();return}S.cur={id:id("measure"),type:"measure",name:"measure",role:"measurement",points:[p2,p2],unit:ensureScale().unit||"mm",is_scale_reference:false};setAnchor(p2);sync(false);draw();return}if(S.tool==="line"){if(S.cur&&S.cur.type==="line"){S.cur.points[1]=p;commit();return}if(S.anchor){let a=clone(S.anchor);S.anchor=null;S.cur={id:id("line"),type:"line",name:"line",role:"trace",points:[a,p]};commit();return}S.cur={id:id("line"),type:"line",name:"line",role:"trace",points:[p,p]};setAnchor(p);sync(false);draw();return}if(S.tool==="rect"){if(S.cur&&S.cur.type==="rect"){S.cur.w=p.x-S.cur.x;S.cur.h=p.y-S.cur.y;commit();return}if(S.anchor){let a=clone(S.anchor);S.anchor=null;S.cur={id:id("rect"),type:"rect",name:"rect",role:"trace",x:a.x,y:a.y,w:p.x-a.x,h:p.y-a.y};commit();return}S.cur={id:id("rect"),type:"rect",name:"rect",role:"trace",x:p.x,y:p.y,w:0,h:0};setAnchor(p);sync(false);draw();return}if(S.tool==="circle"){if(S.cur&&S.cur.type==="circle"){S.cur.r=d(p,{x:S.cur.cx,y:S.cur.cy});commit();return}if(S.anchor){let a=clone(S.anchor);S.anchor=null;S.cur={id:id("circle"),type:"circle",name:"circle",role:"trace",cx:a.x,cy:a.y,r:d(a,p)};commit();return}S.cur={id:id("circle"),type:"circle",name:"circle",role:"trace",cx:p.x,cy:p.y,r:0};setAnchor(p);sync(false);draw();return}if(S.tool==="poly"||S.tool==="mask"||S.tool==="zone"){if(!S.cur){let pts=S.anchor?[clone(S.anchor),p]:[p];S.anchor=null;let typ=S.tool==="mask"?"mask":(S.tool==="zone"?"zone":"poly");S.cur={id:id(typ),type:typ,name:typ,role:typ==="mask"?"ignore_mask":(typ==="zone"?"zone":"trace"),points:pts,closed:typ==="zone"};if(typ==="zone")ensureZoneStyle(S.cur,S.shapes.length)}else{S.cur.points.push(p);if(S.cur.type==="zone")S.cur.closed=true}setAnchor(lastPoint(S.cur));sync(false);draw();return}if(S.tool==="pen"){addPen(p,e);setAnchor(lastPoint(S.cur));sync(false);draw();return}}
function previewCurrentAt(raw,e){if(!S.cur)return false;let p=snapPoint(raw,{off:e&&e.altKey,includeCurrent:false});if(S.cur.type==="measure"){S.cur.points[1]=measureSnapPoint(raw,e);draw();return true}if(S.cur.type==="line"){S.cur.points[1]=p;draw();return true}if(S.cur.type==="rect"){S.cur.w=p.x-S.cur.x;S.cur.h=p.y-S.cur.y;draw();return true}if(S.cur.type==="circle"){S.cur.r=d(p,{x:S.cur.cx,y:S.cur.cy});draw();return true}return false}
function svgElementKind(s){if(!s)return"unknown";if(s.type==="line"||s.type==="path")return"path";if(s.type==="station"||s.type==="measure")return"line";if(s.type==="rect")return"rect";if(s.type==="circle")return"circle";if(s.type==="poly"||s.type==="mask"||s.type==="zone")return(s.closed||s.type==="zone")?"polygon":"polyline";return"unknown"}
function shapeGeomSummary(s){if(!s)return{};if(s.type==="path")return{node_count:s.nodes?.length||0,closed:!!s.closed,svg_command:"M + cubic Bezier C segments",json_geometry:"nodes[].x/y with nodes[].in/out handles",sample_export:"sampled_polyline_64",sample_count:64,sampling:"uniform cubic-segment parameter"};if(s.type==="line")return{point_count:s.points?.length||0,svg_command:"M L",json_geometry:"points[0..1]"};if(s.type==="measure")return{point_count:s.points?.length||0,svg_element:"line",json_geometry:"points[0..1], length_px, real_length, unit, scale flags"};if(s.type==="zone")return{point_count:s.points?.length||0,closed:true,svg_element:"polygon",json_geometry:"points[]",zone_semantics:"named translucent AI context zone; may overlap other zones"};if(s.type==="poly"||s.type==="mask")return{point_count:s.points?.length||0,closed:!!s.closed,svg_element:s.closed?"polygon":"polyline",json_geometry:"points[]"};if(s.type==="station")return{svg_element:"line",orientation:s.orientation||"vertical",json_geometry:"canonical x/y plus synchronized x1/y1/x2/y2, station_index, origin_ref, spacing_px"};if(s.type==="rect")return{svg_element:"rect",json_geometry:"x,y,w,h"};if(s.type==="circle")return{svg_element:"circle",json_geometry:"cx,cy,r"};return{}}
