/**
 * AI-CODING NOTE:
 * Responsibility: Convert Manual Trace workspaces into stable single-object multi-view package models and trigger local ZIP export.
 * Inputs: Current calibrated workspace, selected top/side/front view, and stored view snapshots.
 * Outputs: Browser-local .engrove-trace-project downloads; no upload, import, or Tonearm mutation.
 * Safe edits: Preserve legacy project persistence, stable IDs, geometry semantics, and fail-closed validation.
 * Do not: Infer missing origin/scale, discard unsupported geometry silently, or change the v1 contract.
 */
"use strict";
(function(){
const api=globalThis.EngroveTraceProjectPackage,VIEWS=new Set(["top","side","front"]);if(!api)throw new Error("Trace Project Package runtime failed to load.");
const uid=p=>`${p}-${(crypto.randomUUID?.().replace(/-/g,"")||Date.now().toString(36)+Math.random().toString(36).slice(2)).slice(0,24)}`;
function state(){S.project_meta=S.project_meta||{};const p=S.project_meta;p.package_project_id=p.package_project_id||uid("project");p.package_object_id=p.package_object_id||uid("object");p.package_created_at=p.package_created_at||new Date().toISOString();p.package_trace_ids=p.package_trace_ids||{};p.package_views=p.package_views||{};return{projectId:p.package_project_id,objectId:p.package_object_id,createdAt:p.package_created_at,ids:p.package_trace_ids,views:p.package_views}}
function viewType(){const v=$("packageViewType")?.value||"side";if(!VIEWS.has(v))throw new Error(`Unsupported package view: ${v}.`);return v}
function traceId(v){const s=state();return s.ids[v]=s.ids[v]||uid(`trace-${v}`)}
const uniq=a=>[...new Set(a)].sort((x,y)=>x.localeCompare(y));
function frame(){if(!S.frame?.origin)throw new Error("Set the engineering origin before storing a view.");const m={};for(const a of["x","y","z"]){const t=String(S.frame.axes?.[a]||""),q=/^([+-])(image_x|image_y|out_of_screen)$/.exec(t);if(!q)throw new Error(`Invalid ${a.toUpperCase()} axis mapping.`);const k=q[2]==="image_x"?"u":q[2]==="image_y"?"v":"normal";if(m[k])throw new Error(`View axis ${k} is mapped twice.`);m[k]={engineeringAxis:a.toUpperCase(),direction:q[1]==="+"?1:-1,meaning:t}}if(!m.u||!m.v||!m.normal)throw new Error("Map image X, image Y and view normal exactly once.");return{originPx:{x:Number(S.frame.origin.x),y:Number(S.frame.origin.y)},uAxis:m.u,vAxis:m.v,normalAxis:m.normal,pixelConvention:"u_right_v_down",engineeringOriginDatumId:"datum-origin"}}
function calibration(){const s=S.frame?.scale||{},u=Number(s.unit_per_px),px=Number(s.source_length_px),mm=Number(s.source_real_length),id=String(s.reference_measure_id||"");if(!(u>0&&px>0&&mm>0))throw new Error("Set a valid millimetre scale reference.");if(!/^[A-Za-z][A-Za-z0-9._:-]{2,127}$/.test(id))throw new Error("Scale reference lacks a stable ID.");if(Math.abs(mm/px-u)/Math.max(u,mm/px)>1e-9)throw new Error("Scale fields are inconsistent.");return{unit:"mm",unitPerPx:u,referenceMeasurementId:id,sourcePixelLength:px,sourceRealLength:mm,method:"operator_reference",provenance:{source:"Manual Trace operator scale reference",notes:["Browser-local export."]},toleranceMm:Math.max(1e-9,u/2)}}
function payload(x){if(x.type==="path")return{type:"bezier_path",nodes:x.nodes.map(n=>({point:{x:+n.x,y:+n.y},in:n.in?{x:+n.in.x,y:+n.in.y}:null,out:n.out?{x:+n.out.x,y:+n.out.y}:null}))};if(["poly","mask","zone"].includes(x.type))return{type:x.closed||x.type!=="poly"?"polygon":"polyline",points:x.points.map(p=>({x:+p.x,y:+p.y}))};if(x.type==="line")return{type:"line",points:x.points.map(p=>({x:+p.x,y:+p.y}))};if(x.type==="circle")return{type:"circle",center:{x:+x.cx,y:+x.cy},radius:Math.abs(+x.r)};if(x.type==="rect"){const x2=+x.x + +x.w,y2=+x.y + +x.h;return{type:"rectangle",x:Math.min(+x.x,x2),y:Math.min(+x.y,y2),width:Math.abs(+x.w),height:Math.abs(+x.h)}}throw new Error(`Unsupported package geometry: ${x.type}.`)}
function role(x){const k=String(x.semantic?.feature_kind||"");if(x.type==="mask"||x.role==="ignore")return"ignore_mask";if(x.type==="zone")return"semantic_zone";if(k==="centerline"||k==="baseline")return"centerline";if(k==="hole"||k==="bore")return"hole";if(k==="slot")return"slot";if(k==="inner_contour")return"inner_contour";return"outer_contour"}
const feature=r=>({outer_contour:"silhouette",inner_contour:"cutout",centerline:"center_axis",slot:"cutout",hole:"bore",ignore_mask:"occlusion",semantic_zone:"semantic_region"}[r]||"unknown");
function geometry(vf,c){ensureAllMeta();const cs=S.shapes.filter(x=>!["measure","station"].includes(x.type)&&x.role!=="datum"&&x.semantic?.feature_kind!=="datum");if(!cs.length)throw new Error("At least one contour is required.");const contours=cs.map((x,i)=>{const r=role(x),g=payload(x);return{contourId:x.id,name:x.name||x.id,description:x.description||`Manual Trace contour ${x.id}.`,geometry:g,closed:["polygon","circle","rectangle"].includes(g.type)||!!x.closed,role:r,featureKind:feature(r),references:[],sourceSvgElement:null,status:i?"secondary":"primary"}});const stations=S.shapes.filter(x=>x.type==="station").sort((a,b)=>(+a.station_index||0)-(+b.station_index||0)||String(a.id).localeCompare(String(b.id))).map((x,i)=>{const va=(x.orientation||"vertical")==="horizontal"?"v":"u",line=va==="u"?"v":"u",value=va==="u"?Number(x.x??x.x1):Number(x.y??x.y1),map=va==="u"?vf.uAxis:vf.vAxis,origin=va==="u"?vf.originPx.x:vf.originPx.y,use=map.engineeringAxis==="X";return{stationId:x.id,name:x.name||`station_${i}`,index:i,orientation:line==="u"?vf.uAxis:vf.vAxis,definition:{viewAxis:va,valuePx:value},engineeringPosition:{xMm:use?(value-origin)*c.unitPerPx*map.direction:0,derived:true,derivation:use?"Derived from calibrated engineering X.":"Preserved annotation outside engineering X."},references:[],usage:use?"longitudinal_loft_station":"annotation",geometricUse:use?"used_for_geometry":"preserved_as_provenance"}});return{primaryContourId:contours[0].contourId,contours,stations,datums:[],relations:[]}}
function media(){const t=/^data:([^;,]+)/.exec(S.img?.dataUrl||"")?.[1]?.toLowerCase();return["image/png","image/jpeg","image/webp"].includes(t)?t:"image/png"}
function assets(id,legacy){const a=[],r={sourceImageAssetId:null,sourceSvgAssetId:null,sidecarAssetIds:[]};if(S.img?.dataUrl){const type=media(),aid=`${id}:image`,ext=type==="image/jpeg"?"jpg":type.split("/")[1];a.push({assetId:aid,role:"source_image",mediaType:type,path:`assets/images/${id}.${ext}`,dataUrl:S.img.dataUrl,traceIds:[id],originalFileName:S.img.name||`${id}.${ext}`});r.sourceImageAssetId=aid}if(S.svgTrace?.sourceText){const aid=`${id}:svg`;a.push({assetId:aid,role:"source_svg",mediaType:"image/svg+xml",path:`assets/svg/${id}-source.svg`,text:S.svgTrace.sourceText,traceIds:[id],originalFileName:S.svgTrace.sourceName||`${id}.svg`});r.sourceSvgAssetId=aid}const sid=`${id}:legacy`;a.push({assetId:sid,role:"sidecar",mediaType:"application/json",path:`assets/sidecars/${id}-manual-trace-v18.json`,text:JSON.stringify(legacy,null,2)+"\n",traceIds:[id],originalFileName:`${id}-manual-trace-v18.json`});r.sidecarAssetIds.push(sid);return{a,r}}
async function capture(){const s=state(),v=viewType(),id=traceId(v),vf=frame(),c=calibration(),legacy=outObj(false),sourceDigest=await api.sha256Hex(api.canonicalJsonBytes(legacy)),ar=assets(id,legacy),trace={schemaVersion:api.PACKAGE_VERSION,traceId:id,objectId:s.objectId,view:{viewType:v,projection:"orthographic",geometricUse:v==="front"?"preserved_as_provenance":"used_for_geometry",viewFrame:vf,sectionBinding:null},calibration:c,geometry:geometry(vf,c),assets:ar.r,provenance:{producer:api.PRODUCER,originalSchema:S.schema_version,sourceFileName:`${id}-manual-trace-v18.json`,sourceDigest,imageDimensions:S.img?{widthPx:+S.img.width,heightPx:+S.img.height}:{widthPx:1,heightPx:1},sourceViewBox:null,sourceSvgBinding:null,traceDescriptions:[legacy.description?.en||"Manual Trace view."],semanticNames:uniq(S.shapes.map(x=>x.name||x.id)),aiHints:["Complete editable workspace is preserved as a sidecar."],references:[],exportedAt:s.createdAt,sourceFields:["image","trace_frame","shapes","auto_trace"]}};s.views[v]=clone({trace,assets:ar.a});status();return s.views[v]}
function records(){return Object.entries(S.project_meta?.package_views||{}).filter(([v,x])=>VIEWS.has(v)&&x?.trace&&Array.isArray(x.assets)).sort(([a],[b])=>a.localeCompare(b))}
function status(msg=""){const e=$("packageViewStatus");if(!e)return;const n=records().map(([v])=>v);e.textContent=msg||(n.length?`${n.length} stored view${n.length==1?"":"s"}: ${n.join(", ")}`:"No package views stored")}
async function model(update=true){if(update)await capture();const s=state(),rs=records();if(!rs.length)throw new Error("Store at least one calibrated view.");const traces=rs.map(([,x])=>clone(x.trace)),all=rs.flatMap(([,x])=>clone(x.assets)),name=String(S.project_meta?.name||safeFileBase(S.img?.name||"Manual Trace project")).trim()||"Manual Trace project",length=Math.max(...traces.map(x=>+x.calibration.sourceRealLength));return{projectId:s.projectId,objectId:s.objectId,name,description:`Manual Trace multi-view project package for ${name}.`,objectType:"generic_object",objectName:name,objectDescription:"One shared physical object represented by orthographic Manual Trace views.",createdAt:s.createdAt,producer:api.PRODUCER,engineeringFrame:{origin:{xMm:0,yMm:0,zMm:0,datumId:"datum-origin"},axes:{x:{meaning:"longitudinal",unitVector:{x:1,y:0,z:0}},y:{meaning:"lateral",unitVector:{x:0,y:1,z:0}},z:{meaning:"vertical",unitVector:{x:0,y:0,z:1}}},handedness:"right",lengthUnit:"mm",objectDirection:{axis:"X",positiveMeaning:"positive longitudinal direction",fromDatum:"datum-origin",toDatum:"datum-positive-x"},datums:[{datumId:"datum-origin",name:"Engineering origin",kind:"point",positionMm:{x:0,y:0,z:0},description:S.frame.origin_metadata?.description||"Manual Trace engineering origin.",references:[]},{datumId:"datum-positive-x",name:"Positive X reference",kind:"point",positionMm:{x:length,y:0,z:0},description:"Positive longitudinal reference.",references:[]}],references:[]},traces,assets:all,provenance:{producer:api.PRODUCER,originalSchema:PROJECT_SCHEMA,sourceFileName:`${safeFileBase(name)}.engrove-trace`,exportedAt:s.createdAt,sourceFields:["project_meta","package_views","workspace"],notes:["Generated locally; no project data was uploaded."]},fieldDisposition:[{sourcePath:"package_views.*.workspace.shapes",status:"used_for_geometry",reason:"Mapped to package geometry.",targetPath:"traces.*.geometry"},{sourcePath:"package_views.*.workspace.trace_frame",status:"used_for_geometry",reason:"Mapped to view frames and calibration.",targetPath:"traces.*.view"},{sourcePath:"package_views.*.workspace",status:"preserved_as_provenance",reason:"Complete workspace retained as sidecar.",targetPath:"assets.sidecars"}]}}
async function store(){try{const x=await capture();status(`${x.trace.view.viewType} view stored; ${records().length} total.`);return x}catch(e){console.error(e);alert(`Store project view failed: ${e.message}`);return null}}
async function exportPackage(){const b=$("exportTraceProject");if(b)b.disabled=true;try{const p=await api.buildZipPackage(await model(true),{readmeText:"Engrove Trace Project Package v1\n\nGenerated locally by Engrove Manual Trace.\n"});api.downloadZip(S.project_meta?.name||"engrove_trace_project",p.zipBytes)}catch(e){console.error(e);alert(`Project package export failed: ${e.message}`)}finally{if(b)b.disabled=false}}
$("storePackageView")?.addEventListener("click",store);$("exportTraceProject")?.addEventListener("click",exportPackage);$("packageViewType")?.addEventListener("change",()=>status());status();globalThis.captureCurrentPackageView=capture;globalThis.manualTraceProjectModelFromWorkspace=model;globalThis.exportTraceProjectPackage=exportPackage;
})();
