/**
 * AI-CODING NOTE:
 * Responsibility: Manual Trace shared state and function definitions, chunk 3 of 7.
 * Dependency: Classic scripts share one global lexical environment and must load in numeric order.
 * Safe edits: Preserve identifiers, ordering, schemas, provenance, and browser-local behavior.
 * Do not: Load independently, reorder scripts, or weaken SVG sanitization.
 */
"use strict";
function candidateShape(c,cfg,index){
 let pts=simplifyPoints(c.points,cfg.simplifyTol,c.closed),base={id:c.tracedShapeId||id("svgtrace"),name:(c.elementId||c.label||`svg_surface_${String(index+1).padStart(3,"0")}`).replace(/[^\w.-]+/g,"_"),role:"trace",closed:!!c.closed,description:`Auto-traced from SVG object ${c.label}. Correct with Select/Edit, Add Node or Delete Node.`,semantic:{standard_name:c.elementId||c.label,display_name:c.label,feature_kind:c.closed?"outer_contour":"other",ai_hint:"Direct vector trace from an SVG geometry object; operator may refine nodes."},references:[{relation:"derived_from",target:"image",note:`SVG ${ensureSvgTrace().sourceName||"source"}`}],style:{stroke:C.path,width:1.4},source_svg:{candidate_id:c.id,source_name:ensureSvgTrace().sourceName,element_id:c.elementId,tag:c.tag,fill:c.fill,stroke:c.stroke,closed:c.closed,area_px2:c.area,length_px:c.length,sample_step_px:cfg.sampleStep,simplify_tolerance_px:cfg.simplifyTol}};
 if(cfg.output==="path"){
  base.type="path";base.nodes=pts.map(p=>({x:p.x,y:p.y,in:{x:p.x,y:p.y},out:{x:p.x,y:p.y},auto:true,mode:"smooth"}));autoSmoothPath(base,base.closed)
 }else{base.type="poly";base.points=pts;base.style.stroke=C.poly}
 return ensureShapeMeta(base,S.shapes.length)
}
function traceSvgCandidates(cands){let list=(cands||[]).filter(c=>c&&Array.isArray(c.points)&&c.points.length>=2);if(!list.length){alert("Source geometry is not available in this JSON-only session. Open / detect the source SVG again.");return}let cfg=readSvgSettings(true);hist();list.forEach((c,i)=>{let made=candidateShape(c,cfg,i),ix=c.tracedShapeId?S.shapes.findIndex(s=>s.id===c.tracedShapeId):-1;if(ix>=0){let old=S.shapes[ix];made.id=old.id;made.name=old.name||made.name;made.description=old.description||made.description;made.references=old.references?.length?old.references:made.references;made.semantic=old.semantic||made.semantic;made.source_svg={...(made.source_svg||{}),...(old.source_svg||{})};S.shapes[ix]=made}else{S.shapes.push(made);c.tracedShapeId=made.id}c.status="include";S.sel=made.id});repairSvgTraceLinks();sync()}
function traceActiveSvg(){let c=activeSvgCandidate();if(c)traceSvgCandidates([c])}
function traceIncludedSvg(){traceSvgCandidates(ensureSvgTrace().candidates.filter(c=>c.status==="include"))}
function renderAutoTracePanel(){let st=ensureSvgTrace(),cfg=st.settings||{};repairSvgTraceLinks();if($("svgDetectMode"))$("svgDetectMode").value=cfg.mode||"filled";if($("svgOutputType"))$("svgOutputType").value=cfg.output||"poly";if($("svgSampleStep"))$("svgSampleStep").value=cfg.sampleStep??2.5;if($("svgSimplifyTol"))$("svgSimplifyTol").value=cfg.simplifyTol??1.5;if($("svgMinArea"))$("svgMinArea").value=cfg.minArea??4;if($("svgShowCandidates"))$("svgShowCandidates").checked=st.show!==false;let inc=st.candidates.filter(c=>c.status==="include").length,ign=st.candidates.filter(c=>c.status==="ignore").length,tr=st.candidates.filter(c=>c.tracedShapeId).length;if($("svgTraceStatus"))$("svgTraceStatus").innerHTML=st.sourceName?`<strong>${escapeAttr(st.sourceName)}</strong> · ${st.candidates.length} objects · ${inc} included · ${ign} ignored · ${tr} traced`:"Load an SVG with clear filled/stroked objects.";let box=$("svgCandidateList");if(!box)return;box.innerHTML="";st.candidates.forEach(c=>{let row=document.createElement("div");row.className="svgCand"+(c.id===st.activeId?" on":"")+(c.status==="ignore"?" ignore":"")+(c.tracedShapeId?" traced":"");let ck=document.createElement("input");ck.type="checkbox";ck.checked=c.status==="include";ck.onclick=e=>{e.stopPropagation();setSvgCandidateStatus(c,ck.checked?"include":"ignore")};let text=document.createElement("div"),title=document.createElement("div"),meta=document.createElement("div");title.textContent=c.label;meta.className="meta";let metric=c.area?c.area.toFixed(0)+" px²":(Number(c.length)||0).toFixed(1)+" px";meta.textContent=`${c.tag} · ${c.closed?"closed":"open"} · ${metric}${c.unavailable?" · re-detect source SVG":""}`;text.append(title,meta);let b=document.createElement("button");b.textContent=c.unavailable?"Re-detect":(c.tracedShapeId?"Update":"Trace");b.disabled=!!c.unavailable;b.title=c.unavailable?"Open / detect the source SVG to restore editable candidate geometry.":"";b.onclick=e=>{e.stopPropagation();ensureSvgTrace().activeId=c.id;traceSvgCandidates([c])};row.onclick=()=>{st.activeId=c.id;renderAutoTracePanel();draw()};row.ondblclick=()=>{if(!c.unavailable)traceSvgCandidates([c])};row.append(ck,text,b);box.appendChild(row)})}
function focusActiveSvg(){let c=activeSvgCandidate();if(!c)return;let r=stage.getBoundingClientRect(),pad=40,sw=Math.max(1,c.bbox.w),sh=Math.max(1,c.bbox.h),z=Math.min((r.width-pad*2)/sw,(r.height-pad*2)/sh);S.view.s=Math.max(.01,Math.min(64,z));S.view.x=(r.width-(c.bbox.x*2+c.bbox.w)*S.view.s)/2;S.view.y=(r.height-(c.bbox.y*2+c.bbox.h)*S.view.s)/2;draw()}
function clearSvgCandidates(){let st=ensureSvgTrace();st.candidates=[];st.activeId=null;st.sourceText=null;st.sourceName=null;renderAutoTracePanel();draw()}
function editableShapeAt(p){let s=sel();if(s&&["poly","path"].includes(s.type))return s;let best=null,bd=Infinity;S.shapes.filter(x=>["poly","path"].includes(x.type)).forEach(x=>{let q=shapeDist(x,p);if(q<bd){bd=q;best=x}});return bd<20/S.view.s?best:null}
function projOnSeg(p,a,b){let vx=b.x-a.x,vy=b.y-a.y,t=((p.x-a.x)*vx+(p.y-a.y)*vy)/((vx*vx+vy*vy)||1);t=Math.max(0,Math.min(1,t));return{x:a.x+vx*t,y:a.y+vy*t,t,dist:Math.sqrt(sqSegDist(p,a,b))}}
function cubicPointAt(a,c1,c2,b,t){let m=1-t;return{x:m*m*m*a.x+3*m*m*t*c1.x+3*m*t*t*c2.x+t*t*t*b.x,y:m*m*m*a.y+3*m*m*t*c1.y+3*m*t*t*c2.y+t*t*t*b.y}}
function mixPoint(a,b,t){return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}}
function smartInsertNode(p){let s=editableShapeAt(p);if(!s)return;hist();S.sel=s.id;if(s.type==="poly"){let best={d:Infinity,i:1,p};let n=s.points.length,lim=n-1+(s.closed?1:0);for(let k=0;k<lim;k++){let i=k,j=(k+1)%n,q=projOnSeg(p,s.points[i],s.points[j]);if(q.dist<best.d)best={d:q.dist,i:j===0?n:j,p:{x:q.x,y:q.y}}}s.points.splice(best.i,0,best.p)}else{let ns=s.nodes,n=ns.length,best={d:Infinity,seg:0,t:.5};let lim=n-1+(s.closed?1:0);for(let k=0;k<lim;k++){let a=ns[k],b=ns[(k+1)%n],c1=a.out||a,c2=b.in||b;for(let q=1;q<=30;q++){let t=q/30,z=cubicPointAt(a,c1,c2,b,t),dd=d(p,z);if(dd<best.d)best={d:dd,seg:k,t}}}let i=best.seg,j=(i+1)%n,a=ns[i],b=ns[j],p0={x:a.x,y:a.y},p1=a.out||p0,p2=b.in||{x:b.x,y:b.y},p3={x:b.x,y:b.y},t=best.t,A=mixPoint(p0,p1,t),B=mixPoint(p1,p2,t),C=mixPoint(p2,p3,t),D=mixPoint(A,B,t),E=mixPoint(B,C,t),F=mixPoint(D,E,t);a.out=A;b.in=C;let nn={x:F.x,y:F.y,in:D,out:E,auto:false,mode:"smooth"};if(j===0)ns.push(nn);else ns.splice(j,0,nn)}sync()}
function smartDeleteNode(p){let s=editableShapeAt(p);if(!s)return;let arr=s.type==="poly"?s.points:s.nodes,min=s.closed?3:2;if(arr.length<=min)return;let bi=-1,bd=Infinity;arr.forEach((n,i)=>{let q=d(p,n);if(q<bd){bd=q;bi=i}});if(bi<0||bd>22/S.view.s)return;hist();arr.splice(bi,1);S.sel=s.id;if(s.type==="path"&&arr.some(n=>n.auto!==false))autoSmoothPath(s,s.closed);sync()}
function smartSimplifySelected(){let s=sel();if(!s||!["poly","path"].includes(s.type))return;let cfg=readSvgSettings(true),pts=s.type==="poly"?s.points:sample(s,5),simple=simplifyPoints(pts,cfg.simplifyTol,s.closed);hist();if(s.type==="poly")s.points=simple;else{s.nodes=simple.map(p=>({x:p.x,y:p.y,in:{x:p.x,y:p.y},out:{x:p.x,y:p.y},auto:true,mode:"smooth"}));autoSmoothPath(s,s.closed)}sync()}
function reverseSelectedShape(){let s=sel();if(!s||!["poly","path"].includes(s.type))return;hist();if(s.type==="poly")s.points.reverse();else{s.nodes.reverse();s.nodes.forEach(n=>{let q=n.in;n.in=n.out;n.out=q})}sync()}
function draw(){let r=stage.getBoundingClientRect();cx.clearRect(0,0,r.width,r.height);grid();cx.save();cx.translate(S.view.x,S.view.y);cx.scale(S.view.s,S.view.s);if(S.img)cx.drawImage(S.img._im,0,0);else{cx.fillStyle="#0c121d";cx.fillRect(0,0,1000,700)}drawSvgCandidates();drawFrame();S.shapes.forEach(s=>shape(s,s.id===S.sel));if(S.cur)shape(S.cur,true,true);snapDraw();cx.restore()}
function stroke(s,selected,temp){cx.lineWidth=(selected?2.2:(s.style?.width||1.4))/S.view.s;cx.strokeStyle=temp?"#fff":selected?C.sel:(s.style?.stroke||C[s.type]||C.path);cx.fillStyle=s.style?.fill||C[s.type]||C.path;cx.setLineDash(s.role==="ignore_mask"?[8/S.view.s,5/S.view.s]:[])}
function pt(p,col,r=4){cx.save();cx.fillStyle=col;cx.strokeStyle="#111";cx.lineWidth=1/S.view.s;cx.beginPath();cx.arc(p.x,p.y,r/S.view.s,0,Math.PI*2);cx.fill();cx.stroke();cx.restore()}
function shape(s,selected=false,temp=false){cx.save();stroke(s,selected,temp);cx.beginPath();if(s.type==="station"){let ori=s.orientation||"vertical";if(ori==="horizontal"){let y=s.y??s.y1??0;cx.moveTo(s.x1??0,y);cx.lineTo(s.x2??(S.img?.width||1000),y);cx.stroke();cx.save();cx.fillStyle=s.style?.stroke||"#5d7cff";cx.font=`${11/S.view.s}px Segoe UI`;cx.fillText(s.name||"station",(s.x1??0)+4/S.view.s,y-4/S.view.s);cx.restore()}else{cx.moveTo(s.x,s.y1??0);cx.lineTo(s.x,s.y2??(S.img?.height||1000));cx.stroke();cx.save();cx.fillStyle=s.style?.stroke||"#5d7cff";cx.font=`${11/S.view.s}px Segoe UI`;cx.fillText(s.name||"station",s.x+4/S.view.s,(s.y1??0)+16/S.view.s);cx.restore()}}else if(s.type==="line"){cx.moveTo(s.points[0].x,s.points[0].y);cx.lineTo(s.points[1].x,s.points[1].y);cx.stroke()}else if(s.type==="measure"){let a=s.points[0],b=s.points[1];cx.moveTo(a.x,a.y);cx.lineTo(b.x,b.y);cx.stroke();let px=measureLen(s);let mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};cx.save();cx.fillStyle=s.is_scale_reference?"#ff66cc":"#ffd84d";cx.font=`${12/S.view.s}px Segoe UI`;let lbl=(s.is_scale_reference?"REF ":"")+px.toFixed(1)+" px";if(s.real_length)lbl+=" = "+Number(s.real_length).toFixed(3)+" "+(s.unit||"mm");cx.fillText(lbl,mid.x+6/S.view.s,mid.y-6/S.view.s);cx.restore()}else if(s.type==="rect")cx.strokeRect(s.x,s.y,s.w,s.h);else if(s.type==="circle"){cx.arc(s.cx,s.cy,Math.abs(s.r),0,Math.PI*2);cx.stroke()}else if(s.type==="poly"||s.type==="mask"||s.type==="zone"){if(s.points.length){cx.moveTo(s.points[0].x,s.points[0].y);s.points.slice(1).forEach(p=>cx.lineTo(p.x,p.y));if(s.closed||s.type==="zone")cx.closePath();if(s.type==="zone"){cx.save();cx.globalAlpha=s.style?.fill_alpha??0.18;cx.fillStyle=s.style?.fill||C.zone;cx.fill();cx.restore();cx.stroke()}else{cx.stroke();if(s.type==="mask"){cx.globalAlpha=.09;cx.fill();cx.globalAlpha=1}}}}else if(s.type==="path")pathDraw(s,true);cx.setLineDash([]);if((selected||temp)&&S.pts)handles(s);cx.restore()}
function pathDraw(s,st=true){if(!s.nodes?.length)return;cx.beginPath();cx.moveTo(s.nodes[0].x,s.nodes[0].y);for(let i=1;i<s.nodes.length;i++){let a=s.nodes[i-1],b=s.nodes[i],c1=a.out||a,c2=b.in||b;cx.bezierCurveTo(c1.x,c1.y,c2.x,c2.y,b.x,b.y)}if(s.closed&&s.nodes.length>2){let a=s.nodes.at(-1),b=s.nodes[0],c1=a.out||a,c2=b.in||b;cx.bezierCurveTo(c1.x,c1.y,c2.x,c2.y,b.x,b.y);cx.closePath()}if(st)cx.stroke()}
function corners(s){return[{x:s.x,y:s.y},{x:s.x+s.w,y:s.y},{x:s.x+s.w,y:s.y+s.h},{x:s.x,y:s.y+s.h}]}
function handles(s){if(s.type==="station"){let ori=s.orientation||"vertical";if(ori==="horizontal"){let y=s.y??s.y1??0;pt({x:s.x1??0,y},C.h);pt({x:s.x2??(S.img?.width||1000),y},C.h);pt({x:((s.x1??0)+(s.x2??(S.img?.width||1000)))/2,y},C.out,3.5)}else{pt({x:s.x,y:s.y1??0},C.h);pt({x:s.x,y:s.y2??(S.img?.height||1000)},C.h);pt({x:s.x,y:((s.y1??0)+(s.y2??(S.img?.height||1000)))/2},C.out,3.5)}}else if(s.type==="line")s.points.forEach(p=>pt(p,C.h));else if(s.type==="measure")s.points.forEach((p,i)=>pt(p,i===0?C.in:C.out,5));else if(s.type==="poly"||s.type==="mask"||s.type==="zone")s.points.forEach(p=>pt(p,s.type==="mask"?C.mask:(s.type==="zone"?C.zone:C.h),3.8));else if(s.type==="rect")corners(s).forEach(p=>pt(p,C.h));else if(s.type==="circle"){pt({x:s.cx,y:s.cy},C.h);pt({x:s.cx+s.r,y:s.cy},C.out)}else if(s.type==="path")s.nodes.forEach(n=>{if(n.in){cx.strokeStyle=C.in;cx.lineWidth=1/S.view.s;cx.beginPath();cx.moveTo(n.x,n.y);cx.lineTo(n.in.x,n.in.y);cx.stroke();pt(n.in,C.in,3)}if(n.out){cx.strokeStyle=C.out;cx.lineWidth=1/S.view.s;cx.beginPath();cx.moveTo(n.x,n.y);cx.lineTo(n.out.x,n.out.y);cx.stroke();pt(n.out,C.out,3)}pt(n,C.h,4)})}
function measureLen(s){return(s&&s.points&&s.points.length>=2)?d(s.points[0],s.points[1]):0}
function ensureScale(){S.frame.scale=S.frame.scale||{reference_measure_id:null,unit:"mm",px_per_unit:null,unit_per_px:null,source_length_px:null,source_real_length:null};return S.frame.scale}
function parseNum(v){let n=parseFloat(String(v||"").replace(",", "."));return Number.isFinite(n)?n:null}
function updateMeasurements(){let sc=ensureScale();let ref=S.shapes.find(s=>s.type==="measure"&&s.is_scale_reference)||(sc.reference_measure_id?S.shapes.find(s=>s.id===sc.reference_measure_id):null);if(ref&&ref.real_length>0){let px=measureLen(ref);ref.length_px=px;ref.unit=ref.unit||sc.unit||"mm";sc.reference_measure_id=ref.id;sc.unit=ref.unit;sc.source_length_px=px;sc.source_real_length=ref.real_length;sc.px_per_unit=px/ref.real_length;sc.unit_per_px=ref.real_length/px}for(let m of S.shapes){if(m.type!=="measure")continue;let px=measureLen(m);m.length_px=px;if(sc.px_per_unit&&sc.px_per_unit>0){if(!m.is_scale_reference){m.unit=sc.unit||m.unit||"mm";m.computed_real_length=px/sc.px_per_unit;m.real_length=m.computed_real_length}m.scale_reference_id=sc.reference_measure_id||null}}}
function finalizeMeasure(m){let sc=ensureScale();let px=measureLen(m);m.length_px=px;m.role="measurement";if(!sc.px_per_unit){let real=parseNum(prompt("First measure line: enter real length for scale reference", ""));if(real&&real>0){let unit=prompt("Unit for scale reference",sc.unit||"mm")||"mm";m.real_length=real;m.unit=unit;m.is_scale_reference=true;sc.reference_measure_id=m.id;sc.unit=unit;sc.source_length_px=px;sc.source_real_length=real;sc.px_per_unit=px/real;sc.unit_per_px=real/px}else{m.unit=sc.unit||"mm";m.real_length=null;m.is_scale_reference=false;m.note="No scale reference entered; edit JSON or add a new reference measure."}}else{m.unit=sc.unit||"mm";m.is_scale_reference=false;m.scale_reference_id=sc.reference_measure_id||null;m.real_length=px/sc.px_per_unit;m.computed_real_length=m.real_length}updateMeasurements();return m}
function measureSnapPoint(p,e){S.snapHit=null;if(e&&e.altKey)return p;if(!S.measureSnap)return p;let best=null,bd=1e9,thr=(S.snapPx||14)/S.view.s;let scan=s=>{if(!s||s.type==="measure")return;for(let q of contactPoints(s)){let dd=d(p,q);if(dd<bd){bd=dd;best=q}}};if(S.frame.origin){let dd=d(p,S.frame.origin);if(dd<bd){bd=dd;best=S.frame.origin}}S.shapes.forEach(scan);if(S.cur)scan(S.cur);if(best&&bd<=thr){S.snapHit={x:best.x,y:best.y,dist:bd};return{x:best.x,y:best.y}}return p}
function clean(s){s.created_at=s.created_at||new Date().toISOString();s.style=s.style||{stroke:C[s.type]||C.path,width:s.type==="measure"?1.8:1.4};if(s.type==="rect"){if(s.w<0){s.x+=s.w;s.w=-s.w}if(s.h<0){s.y+=s.h;s.h=-s.h}}return s}
function commit(){commitCurrentKeepAnchor()}
function finish(cl=false){if(!S.cur)return;if(cl)S.cur.closed=true;commitCurrentKeepAnchor({closed:cl})}
