/**
 * AI-CODING NOTE:
 * Responsibility: Render deterministic public HTML, JSON-LD, sitemaps, AI discovery files, and production analytics bootstrap.
 * Inputs: Normalized registry.
 * Outputs: Public strings only.
 * Safe edits: Schema-valid deterministic rendering.
 * Do not: Infer claims, emit source routes, add public build timestamps, or enable analytics outside the configured production hostname.
 * Verification: npm run build && npm run check:seo.
 */
const NL=String.fromCharCode(10);
export const stableJson=(value)=>JSON.stringify(value,null,2)+NL;
const esc=(value)=>String(value).replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const ld=(value)=>JSON.stringify(value).replace(/</g,'\\u003c');
const list=(items,format=(item)=>typeof item==='string'?item:item.description||item.name)=>`<ul>${items.map((item)=>`<li>${esc(format(item))}</li>`).join('')}</ul>`;
const absolute=(site,path)=>`${site.canonicalOrigin}${path}`;
const analyticsTag='<script defer src="/analytics.js"></script>';

function socialMeta({title,description,url,image,robots='index,follow'}){
  return `<title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${esc(robots)}"><link rel="canonical" href="${esc(url)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(url)}"><meta property="og:image" content="${esc(image)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(image)}">`;
}

export function renderAnalytics(registry){
  const config=registry.site.analytics;
  return `/** Generated from config/site.json. Do not edit. */${NL}(()=>{${NL}  'use strict';${NL}  const expectedHost=${JSON.stringify(config.productionHostname)};${NL}  if(!${JSON.stringify(config.enabled)}||window.location.hostname!==expectedHost)return;${NL}  window.dataLayer=window.dataLayer||[];${NL}  function gtag(){window.dataLayer.push(arguments)}${NL}  window.gtag=window.gtag||gtag;${NL}  gtag('js',new Date());${NL}  gtag('config',${JSON.stringify(config.googleAnalyticsMeasurementId)},{anonymize_ip:true});${NL}  const ga=document.createElement('script');ga.async=true;ga.src='https://www.googletagmanager.com/gtag/js?id='+encodeURIComponent(${JSON.stringify(config.googleAnalyticsMeasurementId)});document.head.appendChild(ga);${NL}  (function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src='https://www.clarity.ms/tag/'+i;y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y)})(window,document,'clarity','script',${JSON.stringify(config.microsoftClarityProjectId)});${NL}})();${NL}`;
}

export const runtimeRegistry=(registry)=>({schemaVersion:'1.0.0',canonicalOrigin:registry.site.canonicalOrigin,tools:registry.publicTools.map((tool)=>({slug:tool.slug,url:tool.canonicalUrl,path:tool.canonicalPath,name:tool.name,summary:tool.summary,category:tool.category,tags:tool.tags,updated:tool.updated}))});

export function renderHub(registry){
  const cards=registry.publicTools.map((tool)=>`<a class="card" data-tool-slug="${esc(tool.slug)}" data-search="${esc([tool.name,tool.summary,...tool.tags,...tool.keywords].join(' ').toLowerCase())}" href="${tool.canonicalPath}"><div class="card-head"><span class="card-icon" aria-hidden="true">${esc(tool.icon)}</span><h2 class="card-title">${esc(tool.name)}</h2></div><p class="card-desc">${esc(tool.summary)}</p><div class="card-meta">${tool.tags.map((tag)=>`<span class="tag">${esc(tag)}</span>`).join('')}<time class="card-date" datetime="${tool.updated}">${tool.updated}</time></div></a>`).join(NL);
  const graph={'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':registry.site.organization.id,name:registry.site.organization.name,url:registry.site.organization.url},{'@type':'WebSite','@id':`${registry.site.canonicalOrigin}/#website`,url:`${registry.site.canonicalOrigin}/`,name:registry.site.name,inLanguage:registry.site.language,publisher:{'@id':registry.site.organization.id}},{'@type':'CollectionPage','@id':`${registry.site.canonicalOrigin}/#collection`,url:`${registry.site.canonicalOrigin}/`,name:registry.site.name,isPartOf:{'@id':`${registry.site.canonicalOrigin}/#website`},mainEntity:{'@id':`${registry.site.canonicalOrigin}/#tools`}},{'@type':'ItemList','@id':`${registry.site.canonicalOrigin}/#tools`,itemListElement:registry.publicTools.map((tool,index)=>({'@type':'ListItem',position:index+1,url:tool.canonicalUrl,name:tool.name}))}]};
  const title='Engrove Tools — Browser Engineering Utilities';
  const description='Browser-based engineering and audio utilities with explicit capabilities, limitations, privacy boundaries, and evidence.';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${socialMeta({title,description,url:`${registry.site.canonicalOrigin}/`,image:`${registry.site.canonicalOrigin}/assets/tool-default-1200x630.png`})}<link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${ld(graph)}</script>${analyticsTag}</head><body><header class="site-header"><div class="wrap"><strong>Engrove Tools</strong><button id="theme-toggle" type="button" aria-label="Toggle color theme">Theme</button></div></header><main class="wrap"><section class="intro"><h1>Engrove Tools</h1><p>${esc(description)}</p><p><a href="/llms.txt">llms.txt</a> · <a href="/llms-full.txt">llms-full.txt</a> · <a href="/for-agents.md">for-agents.md</a> · <a href="/agent-capabilities.json">agent capabilities</a></p></section><div class="toolbar"><label for="search">Search <input id="search" type="search"></label><span id="count">${registry.publicTools.length} tools</span></div><section id="grid" class="grid" aria-label="Available tools">${cards}</section><noscript><p>JavaScript is optional; every public tool is linked above.</p></noscript><div id="empty" hidden>No matching tools</div></main><script type="module" src="/app.js"></script></body></html>${NL}`;
}

export function renderTool(registry,tool){
  const faq=tool.faq.length?`<section><h2>Frequently asked questions</h2>${tool.faq.map((item)=>`<article><h3>${esc(item.question)}</h3><p>${esc(item.answer)}</p></article>`).join('')}</section>`:'';
  const related=tool.relatedTools.length?`<section><h2>Related tools</h2><ul>${tool.relatedTools.map((slug)=>{const target=registry.tools.find((candidate)=>candidate.slug===slug);return `<li><a href="${target.canonicalPath}">${esc(target.name)}</a></li>`}).join('')}</ul></section>`:'';
  const graph={'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':registry.site.organization.id,name:registry.site.organization.name,url:registry.site.organization.url},{'@type':'WebSite','@id':`${registry.site.canonicalOrigin}/#website`,url:`${registry.site.canonicalOrigin}/`,name:registry.site.name,publisher:{'@id':registry.site.organization.id}},{'@type':'WebPage','@id':`${tool.canonicalUrl}#webpage`,url:tool.canonicalUrl,name:tool.name,description:tool.summary,inLanguage:tool.language,isPartOf:{'@id':`${registry.site.canonicalOrigin}/#website`}},{'@type':'WebApplication','@id':`${tool.canonicalUrl}#application`,name:tool.name,url:tool.canonicalUrl,description:tool.description,applicationCategory:tool.category,operatingSystem:'Web browser',isAccessibleForFree:tool.access.cost==='free'},{'@type':'BreadcrumbList','@id':`${tool.canonicalUrl}#breadcrumbs`,itemListElement:[{'@type':'ListItem',position:1,name:registry.site.name,item:`${registry.site.canonicalOrigin}/`},{'@type':'ListItem',position:2,name:tool.name,item:tool.canonicalUrl}]},...(tool.faq.length?[{'@type':'FAQPage','@id':`${tool.canonicalUrl}#faq`,mainEntity:tool.faq.map((item)=>({'@type':'Question',name:item.question,acceptedAnswer:{'@type':'Answer',text:item.answer}}))}]:[])]};
  const title=`${tool.name} — Engrove Tools`;
  const image=absolute(registry.site,tool.ogImage);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${socialMeta({title,description:tool.summary,url:tool.canonicalUrl,image,robots:tool.robots})}<link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${ld(graph)}</script>${analyticsTag}</head><body><main class="wrap"><nav aria-label="Breadcrumb"><a href="/">Engrove Tools</a> / ${esc(tool.name)}</nav><h1>${esc(tool.name)}</h1><p>${esc(tool.summary)}</p><section><h2>What this tool does</h2><p>${esc(tool.description)}</p>${list(tool.capabilities)}</section><section><h2>Supported inputs</h2>${list(tool.inputs,(item)=>`${item.name}: ${item.description}`)}</section><section><h2>Produced outputs</h2>${list(tool.outputs,(item)=>`${item.name}: ${item.description}`)}</section><section><h2>When to use</h2>${list(tool.whenToUse)}</section><section><h2>When not to use</h2>${list(tool.whenNotToUse)}</section><section><h2>Limitations</h2>${list(tool.limitations)}</section><section><h2>Privacy and processing</h2><p>Processing: ${esc(tool.privacy.processing)}. Server storage of application user data: ${tool.privacy.storesApplicationUserDataOnServer?'yes':'no'}. Account required: ${tool.privacy.requiresAccount?'yes':'no'}. OAuth required: ${tool.privacy.requiresOAuth?'yes':'no'}.</p></section><section><h2>Claim boundaries</h2><h3>Supported claims</h3>${list(tool.claims.mayClaim)}<h3>Negative boundaries</h3>${list(tool.claims.negativeClaimBoundaries)}<h3>Claims that must not be made</h3>${list(tool.claims.mustNotClaim)}</section>${faq}<section><h2>Evidence and source links</h2><ul>${tool.evidence.map((item)=>`<li><a href="${esc(item.url)}" rel="noopener">${esc(item.label)}</a></li>`).join('')}</ul></section>${related}<section><h2>Launch tool</h2><p><a href="${tool.appPath}">Open ${esc(tool.shortName)}</a></p></section></main></body></html>${NL}`;
}

function toolCorpus(tool){return `## ${tool.name}${NL}${NL}${tool.description}${NL}${NL}Canonical URL: ${tool.canonicalUrl}${NL}Updated: ${tool.updated}${NL}${NL}Capabilities:${NL}${tool.capabilities.map((item)=>`- ${item}`).join(NL)}${NL}${NL}Inputs:${NL}${tool.inputs.map((item)=>`- ${item.name} (${item.type}${item.required?', required':''}): ${item.description}`).join(NL)}${NL}${NL}Outputs:${NL}${tool.outputs.map((item)=>`- ${item.name} (${item.type}): ${item.description}`).join(NL)}${NL}${NL}When to use:${NL}${tool.whenToUse.map((item)=>`- ${item}`).join(NL)}${NL}${NL}When not to use:${NL}${tool.whenNotToUse.map((item)=>`- ${item}`).join(NL)}${NL}${NL}Limitations:${NL}${tool.limitations.map((item)=>`- ${item}`).join(NL)}${NL}${NL}Privacy:${NL}- Processing: ${tool.privacy.processing}${NL}- Stores application user data on server: ${tool.privacy.storesApplicationUserDataOnServer}${NL}- Requires account: ${tool.privacy.requiresAccount}${NL}- Requires OAuth: ${tool.privacy.requiresOAuth}${NL}${NL}May claim:${NL}${tool.claims.mayClaim.map((item)=>`- ${item}`).join(NL)}${NL}${NL}Negative claim boundaries:${NL}${tool.claims.negativeClaimBoundaries.map((item)=>`- ${item}`).join(NL)}${NL}${NL}Must not claim:${NL}${tool.claims.mustNotClaim.map((item)=>`- ${item}`).join(NL)}${NL}${NL}Evidence:${NL}${tool.evidence.map((item)=>`- ${item.label}: ${item.url}`).join(NL)}${NL}${NL}Related tools:${NL}${tool.relatedTools.map((item)=>`- ${item}`).join(NL)}${NL}`;}

export function renderDiscovery(registry){
  const urls=[`${registry.site.canonicalOrigin}/`,...registry.publicTools.map((tool)=>tool.canonicalUrl)];
  const llms=`# ${registry.site.name}${NL}${NL}Canonical origin: ${registry.site.canonicalOrigin}${NL}${NL}## Tools${NL}${registry.publicTools.map((tool)=>`- [${tool.name}](${tool.canonicalUrl}): ${tool.summary}`).join(NL)}${NL}${NL}Claim boundaries: public static resources are available; no public backend API, server MCP endpoint, OAuth, user accounts, commerce, certification, or guaranteed accuracy is provided.${NL}${NL}Full corpus: ${registry.site.canonicalOrigin}/llms-full.txt${NL}`;
  const full=`# ${registry.site.name} full public corpus${NL}${NL}${registry.publicTools.map(toolCorpus).join(`${NL}---${NL}`)}`;
  const tools=registry.publicTools.map((tool)=>({slug:tool.slug,name:tool.name,url:tool.canonicalUrl,summary:tool.summary,description:tool.description,category:tool.category,tags:tool.tags,keywords:tool.keywords,updated:tool.updated,capabilities:tool.capabilities,inputs:tool.inputs,outputs:tool.outputs,whenToUse:tool.whenToUse,whenNotToUse:tool.whenNotToUse,limitations:tool.limitations,privacy:tool.privacy,access:tool.access,claims:tool.claims,faq:tool.faq,evidence:tool.evidence,relatedTools:tool.relatedTools}));
  const output={'robots.txt':`User-agent: *${NL}Allow: /${NL}${NL}Content-Signal: search=yes, ai-input=yes, ai-train=no${NL}${NL}Sitemap: ${registry.site.canonicalOrigin}/sitemap.xml${NL}`,'sitemap.xml':`<?xml version="1.0" encoding="UTF-8"?>${NL}<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${registry.site.canonicalOrigin}/</loc></url>${registry.publicTools.map((tool)=>`<url><loc>${tool.canonicalUrl}</loc><lastmod>${tool.updated}</lastmod></url>`).join('')}</urlset>${NL}`,'sitemap.json':stableJson({schemaVersion:'1.0.0',urls}),'sitemap.txt':urls.join(NL)+NL,'llms.txt':llms,'llms-full.txt':full,'for-agents.md':full,'for-agents/index.html':`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Engrove Tools for agents</title><meta name="description" content="Machine-readable public tool capabilities, limitations, evidence, and claim boundaries."><meta name="robots" content="index,follow"><link rel="canonical" href="${registry.site.canonicalOrigin}/for-agents/">${analyticsTag}</head><body><main><h1>Engrove Tools for agents</h1><pre>${esc(full)}</pre></main></body></html>${NL}`,'ai.json':stableJson({schemaVersion:'1.0.0',site:registry.site,tools}),'agent-capabilities.json':stableJson({schemaVersion:'1.0.0',canonicalOrigin:registry.site.canonicalOrigin,publicStaticDataResources:true,publicProgrammaticBackendApi:false,hasBrowserNativeModelContextTools:false,hasServerMcpEndpoint:false,hasOAuth:false,hasUserAccounts:false,hasCommerce:false,tools:tools.map((tool)=>({slug:tool.slug,url:tool.url}))}),'public-info.json':stableJson({schemaVersion:'1.0.0',name:registry.site.name,canonicalOrigin:registry.site.canonicalOrigin,contentPolicy:registry.site.contentPolicy,tools:tools.map((tool)=>({slug:tool.slug,name:tool.name,url:tool.url,summary:tool.summary,updated:tool.updated}))}),'.well-known/engrove-tools.json':stableJson({schemaVersion:'1.0.0',canonicalOrigin:registry.site.canonicalOrigin,tools:tools.map((tool)=>({slug:tool.slug,url:tool.url}))}),'.well-known/agent-skills/index.json':stableJson({schemaVersion:'1.0.0',skills:[{id:'engrove-tools',url:`${registry.site.canonicalOrigin}/.well-known/agent-skills/engrove-tools/SKILL.md`}]}),'.well-known/agent-skills/engrove-tools/SKILL.md':`# Engrove Tools${NL}${NL}Use canonical public pages and structured manifests. Read /agent-capabilities.json before making runtime or API claims. No server MCP endpoint is provided.${NL}`};
  for(const tool of tools){output[`tools/${tool.slug}/tool.ai.json`]=stableJson({schemaVersion:'1.0.0',tool});output[`tools/${tool.slug}/tool.md`]=`# ${tool.name}${NL}${NL}${tool.summary}${NL}${NL}${toolCorpus(tool)}`;}
  return output;
}
