/**
 * AI-CODING NOTE:
 * Responsibility: Render deterministic public HTML, JSON-LD, sitemaps, and AI discovery files.
 * Inputs: Normalized registry.
 * Outputs: Public strings only.
 * Safe edits: Schema-valid deterministic rendering.
 * Do not: Infer claims, emit source routes, or add public build timestamps.
 * Verification: npm run build && npm run check:seo.
 */
const NL=String.fromCharCode(10);
export const stableJson=(value)=>JSON.stringify(value,null,2)+NL;
const esc=(value)=>String(value).replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const ld=(value)=>JSON.stringify(value).replace(/</g,'\\u003c');
const list=(items)=>`<ul>${items.map((item)=>`<li>${esc(typeof item==='string'?item:item.description||item.name)}</li>`).join('')}</ul>`;
export const runtimeRegistry=(registry)=>({schemaVersion:'1.0.0',canonicalOrigin:registry.site.canonicalOrigin,tools:registry.publicTools.map((tool)=>({slug:tool.slug,url:tool.canonicalUrl,path:tool.canonicalPath,name:tool.name,summary:tool.summary,category:tool.category,tags:tool.tags,updated:tool.updated}))});

export function renderHub(registry){
  const cards=registry.publicTools.map((tool)=>`<a class="card" data-tool-slug="${esc(tool.slug)}" data-search="${esc([tool.name,tool.summary,...tool.tags,...tool.keywords].join(' ').toLowerCase())}" href="${tool.canonicalPath}"><div class="card-head"><span class="card-icon" aria-hidden="true">${esc(tool.icon)}</span><h2 class="card-title">${esc(tool.name)}</h2></div><p class="card-desc">${esc(tool.summary)}</p><div class="card-meta">${tool.tags.map((tag)=>`<span class="tag">${esc(tag)}</span>`).join('')}<time class="card-date" datetime="${tool.updated}">${tool.updated}</time></div></a>`).join(NL);
  const graph={'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':registry.site.organization.id,name:registry.site.organization.name,url:registry.site.organization.url},{'@type':'WebSite','@id':`${registry.site.canonicalOrigin}/#website`,url:`${registry.site.canonicalOrigin}/`,name:registry.site.name,publisher:{'@id':registry.site.organization.id}},{'@type':'CollectionPage','@id':`${registry.site.canonicalOrigin}/#collection`,url:`${registry.site.canonicalOrigin}/`,name:registry.site.name},{'@type':'ItemList',itemListElement:registry.publicTools.map((tool,index)=>({'@type':'ListItem',position:index+1,url:tool.canonicalUrl,name:tool.name}))}]};
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Engrove Tools — Browser Engineering Utilities</title><meta name="description" content="Browser-based engineering and audio utilities with explicit capabilities and limitations."><meta name="robots" content="index,follow"><link rel="canonical" href="${registry.site.canonicalOrigin}/"><meta property="og:type" content="website"><meta property="og:title" content="Engrove Tools"><meta property="og:description" content="Browser-based engineering and audio utilities."><meta property="og:url" content="${registry.site.canonicalOrigin}/"><meta property="og:image" content="${registry.site.canonicalOrigin}/assets/tool-default-1200x630.png"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${ld(graph)}</script></head><body><header class="site-header"><div class="wrap"><strong>Engrove Tools</strong><button id="theme-toggle" type="button" aria-label="Toggle color theme">Theme</button></div></header><main class="wrap"><section class="intro"><h1>Engrove Tools</h1><p>Static browser-based engineering and audio utilities with explicit inputs, outputs, limitations, privacy boundaries, and evidence.</p><p><a href="/llms.txt">llms.txt</a> · <a href="/for-agents.md">for-agents.md</a> · <a href="/agent-capabilities.json">agent capabilities</a></p></section><div class="toolbar"><label for="search">Search <input id="search" type="search"></label><span id="count">${registry.publicTools.length} tools</span></div><section id="grid" class="grid">${cards}</section><noscript><p>JavaScript is optional; every public tool is linked above.</p></noscript><div id="empty" hidden>No matching tools</div></main><script type="module" src="/app.js"></script></body></html>${NL}`;
}

export function renderTool(registry,tool){
  const faq=tool.faq.length?`<section><h2>FAQ</h2>${tool.faq.map((item)=>`<article><h3>${esc(item.question)}</h3><p>${esc(item.answer)}</p></article>`).join('')}</section>`:'';
  const graph={'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':registry.site.organization.id,name:registry.site.organization.name,url:registry.site.organization.url},{'@type':'WebSite','@id':`${registry.site.canonicalOrigin}/#website`,url:`${registry.site.canonicalOrigin}/`,name:registry.site.name},{'@type':'WebPage','@id':`${tool.canonicalUrl}#webpage`,url:tool.canonicalUrl,name:tool.name,description:tool.summary},{'@type':'WebApplication','@id':`${tool.canonicalUrl}#application`,name:tool.name,url:tool.canonicalUrl,description:tool.description,applicationCategory:tool.category,operatingSystem:'Web browser',isAccessibleForFree:true},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:registry.site.name,item:`${registry.site.canonicalOrigin}/`},{'@type':'ListItem',position:2,name:tool.name,item:tool.canonicalUrl}]},...(tool.faq.length?[{'@type':'FAQPage',mainEntity:tool.faq.map((item)=>({'@type':'Question',name:item.question,acceptedAnswer:{'@type':'Answer',text:item.answer}}))}]:[])]};
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(tool.name)} — Engrove Tools</title><meta name="description" content="${esc(tool.summary)}"><meta name="robots" content="${tool.robots}"><link rel="canonical" href="${tool.canonicalUrl}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(tool.name)}"><meta property="og:description" content="${esc(tool.summary)}"><meta property="og:url" content="${tool.canonicalUrl}"><meta property="og:image" content="${registry.site.canonicalOrigin}${tool.ogImage}"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${ld(graph)}</script></head><body><main class="wrap"><nav><a href="/">Engrove Tools</a> / ${esc(tool.name)}</nav><h1>${esc(tool.name)}</h1><p>${esc(tool.summary)}</p><p>${esc(tool.description)}</p><a href="${tool.appPath}">Launch tool</a><section><h2>What this tool does</h2>${list(tool.capabilities)}</section><section><h2>Supported inputs</h2>${list(tool.inputs)}</section><section><h2>Produced outputs</h2>${list(tool.outputs)}</section><section><h2>When to use</h2>${list(tool.whenToUse)}<h2>When not to use</h2>${list(tool.whenNotToUse)}</section><section><h2>Limitations</h2>${list(tool.limitations)}</section><section><h2>Privacy and processing</h2><p>Processing: ${esc(tool.privacy.processing)}. Server storage: ${tool.privacy.storesApplicationUserDataOnServer?'yes':'no'}.</p></section><section><h2>Claim boundaries</h2>${list(tool.claims.mayClaim)}${list(tool.claims.negativeClaimBoundaries)}${list(tool.claims.mustNotClaim)}</section>${faq}<section><h2>Evidence</h2><ul>${tool.evidence.map((item)=>`<li><a href="${esc(item.url)}">${esc(item.label)}</a></li>`).join('')}</ul></section></main></body></html>${NL}`;
}

export function renderDiscovery(registry){
  const urls=[`${registry.site.canonicalOrigin}/`,...registry.publicTools.map((tool)=>tool.canonicalUrl)];
  const llms=`# ${registry.site.name}${NL}${NL}Canonical origin: ${registry.site.canonicalOrigin}${NL}${NL}## Tools${NL}${registry.publicTools.map((tool)=>`- [${tool.name}](${tool.canonicalUrl}): ${tool.summary}`).join(NL)}${NL}${NL}No public backend API, OAuth, accounts, commerce, certification, or guaranteed accuracy is provided.${NL}`;
  const full=llms+NL+registry.publicTools.map((tool)=>`## ${tool.name}${NL}${NL}${tool.description}${NL}${NL}Capabilities:${NL}${tool.capabilities.map((item)=>`- ${item}`).join(NL)}${NL}${NL}Inputs:${NL}${tool.inputs.map((item)=>`- ${item.name}: ${item.description}`).join(NL)}${NL}${NL}Outputs:${NL}${tool.outputs.map((item)=>`- ${item.name}: ${item.description}`).join(NL)}${NL}${NL}Limitations:${NL}${tool.limitations.map((item)=>`- ${item}`).join(NL)}${NL}${NL}May claim:${NL}${tool.claims.mayClaim.map((item)=>`- ${item}`).join(NL)}${NL}${NL}Negative boundaries:${NL}${tool.claims.negativeClaimBoundaries.map((item)=>`- ${item}`).join(NL)}${NL}`).join(NL);
  const tools=registry.publicTools.map((tool)=>({slug:tool.slug,name:tool.name,url:tool.canonicalUrl,summary:tool.summary,capabilities:tool.capabilities,limitations:tool.limitations,privacy:tool.privacy,claims:tool.claims,evidence:tool.evidence,relatedTools:tool.relatedTools}));
  const output={'robots.txt':`User-agent: *${NL}Allow: /${NL}${NL}Content-Signal: search=yes, ai-input=yes, ai-train=no${NL}${NL}Sitemap: ${registry.site.canonicalOrigin}/sitemap.xml${NL}`,'sitemap.xml':`<?xml version="1.0" encoding="UTF-8"?>${NL}<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map((url)=>`<url><loc>${url}</loc></url>`).join('')}</urlset>${NL}`,'sitemap.json':stableJson({schemaVersion:'1.0.0',urls}),'sitemap.txt':urls.join(NL)+NL,'llms.txt':llms,'llms-full.txt':full,'for-agents.md':full,'for-agents/index.html':`<!doctype html><html lang="en"><head><title>Engrove Tools for agents</title><link rel="canonical" href="${registry.site.canonicalOrigin}/for-agents/"></head><body><pre>${esc(full)}</pre></body></html>${NL}`,'ai.json':stableJson({schemaVersion:'1.0.0',site:registry.site,tools}),'agent-capabilities.json':stableJson({schemaVersion:'1.0.0',canonicalOrigin:registry.site.canonicalOrigin,publicStaticDataResources:true,publicProgrammaticBackendApi:false,hasBrowserNativeModelContextTools:false,hasServerMcpEndpoint:false,hasOAuth:false,hasUserAccounts:false,hasCommerce:false,tools:tools.map((tool)=>({slug:tool.slug,url:tool.url}))}),'public-info.json':stableJson({schemaVersion:'1.0.0',name:registry.site.name,canonicalOrigin:registry.site.canonicalOrigin,contentPolicy:registry.site.contentPolicy,publicToolCount:tools.length}),'.well-known/engrove-tools.json':stableJson({schemaVersion:'1.0.0',canonicalOrigin:registry.site.canonicalOrigin,tools:tools.map((tool)=>({slug:tool.slug,url:tool.url}))}),'.well-known/agent-skills/index.json':stableJson({schemaVersion:'1.0.0',skills:[{id:'engrove-tools',url:`${registry.site.canonicalOrigin}/.well-known/agent-skills/engrove-tools/SKILL.md`}]}),'.well-known/agent-skills/engrove-tools/SKILL.md':`# Engrove Tools${NL}${NL}Use canonical public pages and structured manifests. No server MCP endpoint is provided.${NL}`};
  for(const tool of tools){output[`tools/${tool.slug}/tool.ai.json`]=stableJson({schemaVersion:'1.0.0',tool});output[`tools/${tool.slug}/tool.md`]=`# ${tool.name}${NL}${NL}${tool.summary}${NL}${NL}## Capabilities${NL}${tool.capabilities.map((item)=>`- ${item}`).join(NL)}${NL}${NL}## Limitations${NL}${tool.limitations.map((item)=>`- ${item}`).join(NL)}${NL}`}
  return output;
}
